name: Build Azure SQL Dacpac

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2025-vs2026

    env:
      # Ajusta la ruta a tu archivo .slnx
      SOLUTION_PATH: "PROYECTOBD/PROYECTOBD.sln"
      BUILD_CONFIGURATION: Release

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Asegura compatibilidad con .slnx

      - name: Configurar MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restaurar dependencias
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Compilar Proyecto SQL (Generar Dacpac)
        run: |
          msbuild ${{ env.SOLUTION_PATH }} `
            /p:Configuration=${{ env.BUILD_CONFIGURATION }} `
            /p:OutDir=./artifacts/ `
            /t:Build

      - name: Archivar el Dacpac
        uses: actions/upload-artifact@v4
        with:
          name: sql-package
          path: D:/a/PROYECTO_DB/PROYECTO_DB/PROYECTOBD/artifacts/**/*.dacpac

  deploy:
    runs-on: windows-2025-vs2026
    needs: build # IMPORTANTE: Espera a que el job de build termine con éxito
    
    steps:
      # 1. Descargar el artefacto generado en el paso anterior
      - name: Download Dacpac
        uses: actions/download-artifact@v4
        with:
          name: sql-package
          path: ./downloaded-dacpac

      # 2. Desplegar a Azure SQL
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2
        with:
          # Usa un secreto para tu cadena de conexión
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          
          # Ruta donde se descargó el archivo
          path: './downloaded-dacpac/TuProyecto.dacpac'
          
          # 'Publish' aplica los cambios del dacpac a la base de datos real
          action: 'Publish'
